###
POST http://localhost:9000/api/usersIntern HTTP/1.1
Content-Type: application/json

{
  "_Apellido": "Llican Cardenas",
  "_Carrera": "Ingenieria de Sistemas",
  "_Contraseña": "Awvx6jgK",
  "_Correo": "jair.llican@unmsm.edu.pe",
  "_Enlace_Portafolio": "URL",
  "_Enlace_Presentacion": "URL 2",
  "_Facultad": "Facultad de Ingenieria de Sistemas e Informatica",
  "_Gustos": [
    "Data analysis",
    "PowerBI"
  ],
  "_Nombre": "Jair",
  "_Universidad": "Universidad Nacional Mayor de San Marcos"
}

###
GET http://localhost:9000/api/usersIntern HTTP/1.1

###
GET http://localhost:9000/api/checkEmail_usersIntern?email=jair.llican@unmsm.edu.pe HTTP/1.1

###
GET http://localhost:9000/api/usersIntern_byEmail?email=jair.llican@unmsm.edu.pe HTTP/1.1


###
DELETE http://localhost:9000/api/usersIntern_delete?email=jair1.llican@unmsm.edu.pe HTTP/1.1

###
PUT http://localhost:9000/api/usersIntern_update?email=jair.llican@unmsm.edu.pe HTTP/1.1
Content-Type: application/json

{
  "_Apellido": "Llican Cardenas",
  "_Carrera": "Ingenieria de Sistemas",
  "_Contraseña": "Awvx6jgK",
  "_Correo": "jair.llican@unmsm.edu.pe",
  "_Enlace_Portafolio": "URL",
  "_Enlace_Presentacion": "URL 2",
  "_Facultad": "Facultad de Ingenieria de Sistemas e Informatica",
  "_Gustos": [
    "Data analyst",
    "PowerBI",
    "BI",
    "Tableau"
  ],
  "_Nombre": "Jair",
  "_Universidad": "Universidad Nacional Mayor de San Marcos"
}